title: "CTF & Cybersecurity Blog"
description: "Write-ups and articles on cybersecurity."
baseurl: ""
url: "https://yourgithubusername.github.io"

permalink: /:categories/:title/
highlighter: rouge

collections:
  writeups:
    output: true
  blog:
    output: true

theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
