title: CTF Writeups & Security Research
description: A collection of CTF writeups and cybersecurity articles
url: https://tekila11.github.io/secVlog
baseurl: "secVlog"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  writeups:
    output: true
    permalink: /writeups/:path/
  articles:
    output: true
    permalink: /articles/:path/

defaults:
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock